---
all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
    servers:
      hosts:
        # Add your servers here
        # server1:
        #   ansible_host: 192.168.1.10
